jumpboost:
    jump: 1.7
    dash: 0.5

paste_pivot:
    x: -5933
    y: 65
    z: -3129

schematic_empty:
    - cima_empty

schematic_list_secuency_round_1:
    - cima_r1_1
    - cima_r1_2
    - cima_r1_3
    - cima_r1_4
    - cima_r1_5
    - cima_r1_6
    - cima_r1_7
    -
schematic_list_secuency_round_2:
    - cima_r2_1
    - cima_r2_2
    - cima_r2_3
    - cima_r2_4
    - cima_r2_5

schematic_list_secuency_round_3:
    - cima_r3_1
    - cima_r3_2
    - cima_r3_3
    - cima_r3_4
    - cima_r3_5
