jumpboost:
    jump: 1.7
    dash: 0.5

paste_pivot:
    x: -5933
    y: 65
    z: -3129

schematic_empty:
    - cima_empty

schematic_rounds:
    - cima_round_1
    - cima_round_2
    - cima_round_3
